version: '3.8'

services:
  n8n:
    image: n8nio/n8n:stable
    container_name: n8n
    command: start --tunnel
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./n8n-data:/home/node/.n8n
      - /usr/local/share/.config/
    user: root
    restart: unless-stopped
    networks:
      - ia-rag-stack-net

  ollama:
    image: ollama/ollama:0.1.9
    container_name: ollama
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ia-rag-stack-net
    restart: unless-stopped

networks:
  ia-rag-stack-net:
    driver: bridge
